### ISSUE TITLE
C++ value semantics, RAII, widgets state and life time

### ISSUE THREAD

**Issue by SylvainCorlay** [QuantStack/xwidgets#16]
xeus comms and widgets are meant to have a value semantics.

The behavior is the following

 - when a comm is created, it is registered in the comm manager
 - when a comm is destroyed, it is unregistered from the comm manager.
 - every time we copy a comm, i.e. `xcomm a = b`, we create a new comm with a new ID and an entry in the comm manager. This semantic is different from that of python / ipykernel / ipywidgets. Obviously it is not the case with references
 - however, when we *move* a comm with move constructor, no new ID is used. The address in the comm manager is simply updated.

Now, `open()` and `close()` are still independent operations from the constructor. Morally, we could also call these upon registration and unregistration, and it would probably be **cleaner**.

The issue that remains though, is that `open` can send data and metadata in the `comm_open` message, and it is used by the widgets framework. (We actually do that in xwidgets too when instantiating the comm). However, we still need to implement it in the case of copy and move constructors.

I have the feeling that the collapsing of the opening of the comm and the sending of the initial stat complicates the picture. I am tempted to always send *two* messages, one for the comm_open with no state (and implement full RAII wrt `comm_open` and `comm_close`) and manually send patches.

**Comment by SylvainCorlay** [comment]
Another issue, which is specific to the version 2 of the protocol is that the comm open message *must* have the protocol version number.

This completely prevent comms to open and close themselves with an RAII pattern since comms are agnostic to widgets.

**Comment by SylvainCorlay** [comment]
@jasongrout cf message above. This is an issue that the `comm_open` is the one message to handle the version check.

**Comment by jasongrout** [comment]
We discussed this on the phone. One idea is to make a new target for version 2 protocol.

But really, the comm framework is built so that metadata in the comm open messages can be meaningful. Whether we change ipywidgets or not, that is something to consider.

**Comment by SylvainCorlay** [comment]
Yeah, I have come around on this. Actually, in #20, I have implemented the logic for the widgets to handle the comm open and close. Since it is the same for all widgets (that are final, i.e. concrete types), I will be able to make this a macro.

**Comment by SylvainCorlay** [comment]
Closing !!!
