### ISSUE TITLE
Update to xeus 0.23

### ISSUE THREAD

**Issue by jtpio** [QuantStack/xwidgets#170]
So that `xwidgets` can be installed together with the latest `xeus` and `xeus-cling`.

The recipe will also need to be updated: 

https://github.com/conda-forge/xwidgets-feedstock/blob/56721343c6858fa5c502da7ba2249390ca4fb2fa/recipe/meta.yaml#L25

**Comment by SylvainCorlay** [comment]
This is now fixed in master.
