### ISSUE TITLE
`serialize_state` and `apply_patch` should be protected methods instead of public

### ISSUE THREAD

**Issue by SylvainCorlay** [QuantStack/xwidgets#178]
I tested on a couple of widgets and that seems to work.

This may make it easier to make more symbols private.

**Comment by JohanMabille** [comment]
weird, `serialize_state` is called from the base class `xtransport` which is not a friend of widget classes, I don't understand how it can work.

**Comment by SylvainCorlay** [comment]
Oh maybe the top level has to be public then.

**Comment by JohanMabille** [comment]
I meant, some methods in `xtransport` explicitly call `derived_cast().serialize_state(...)`

**Comment by SylvainCorlay** [comment]
OK, my test was actually only testing for intermediary classes, so not called by xtransport.
