### ISSUE TITLE
x-tensibility to non-xeus kernels?

### ISSUE THREAD

**Issue by spennihana** [QuantStack/xwidgets#48]
In order to drive wider/quicker adoption by existing kernels (without having to re-impl an existing kernel), it would seem reasonable to do one of:

1. mock a xeus kernel so that an existing kernel can port out to xwidgets
2. make (perhaps in xtransport?) xwidgets more flexible so that  mimebundles can be got directly

**Comment by SylvainCorlay** [comment]
@spennihana extensibility without a xeus kernel is difficult because xwidgets relies entirely on the `comm` protocol which is implemented in the xeus library.

However, we do provide a sort of `mock` kernel that allows the creation of the backend only for testing purposes.

**Comment by SylvainCorlay** [comment]
Don't hesitate to hop on the chat room https://gitter.im/QuantStack/Lobby I have been iterating on the bqplot backend today:

![screenshot from 2017-09-21 02-33-07](https://user-images.githubusercontent.com/2397974/30721459-767879f6-9f2c-11e7-8047-ece781659e1b.png)

**Comment by SylvainCorlay** [comment]
Closing as discussion carries on on gitter.
