### ISSUE TITLE
Binary messages

### ISSUE THREAD

**Issue by SylvainCorlay** [QuantStack/xwidgets#50]
The implementation of custom serialization with binary buffers cannot be done in the same way as in python, since the xjson representation does not carry types that may not be json serializable.

**Comment by SylvainCorlay** [comment]
cc @maartenbreddels

**Comment by SylvainCorlay** [comment]
After in-person discussions here is how we were thinking of making it work.

## Curent mechanism

Currently, the serialization and deserialization of patches and full widget states rely upon

The two macros: `XOBJECT_SET_PROPERTY_FROM_PATCH` and `XOBJECT_SET_PATCH_FROM_PROPERTY`, which set or get values of a JSON patch to serialize or deserialize a property.

```cpp
    #define XOBJECT_SET_PROPERTY_FROM_PATCH(name, patch)                   \
    if (patch.find(#name) != patch.end())                                  \
    {                                                                      \
        name = patch.at(#name).get<typename decltype(name)::value_type>(); \
    }

    #define XOBJECT_SET_PATCH_FROM_PROPERTY(name, patch) \
    patch[#name] = this->name();
```

The `get_state` function is called upon state request and Comm opening. It calls the `XOBJECT_SET_PATCH_FROM_PROPERTY` macro editing the JSON patch.

```cpp
    template <class D>
    inline xeus::xjson xobject<D>::get_state() const
    {
        xeus::xjson state;

        XOBJECT_SET_PATCH_FROM_PROPERTY(_model_module, state);
        XOBJECT_SET_PATCH_FROM_PROPERTY(_model_module_version, state);
        // [...]

        return state;
    }
````

Function `XOBJECT_SET_PATCH_FROM_PROPERTY` is also called upon changes of single properties.

```cpp
    template <class D>
    template <class P>
    inline void xtransport<D>::notify(const P& property) const
    {
        if (m_hold != nullptr)
        {
            auto it = m_hold->find(property.name());
            if (it != m_hold->end() && it.value() == property())
            {
                return;
            }
        }
        xeus::xjson state;
        state[property.name()] = property();
        send_patch(std::move(state));
    }
```

Reversely, patches from the frontend are applied with the `XOBJECT_SET_PROPERTY_FROM_PATCH`.

```cpp
    template <class D>
    inline void xobject<D>::apply_patch(const xeus::xjson& patch)
    {
        XOBJECT_SET_PROPERTY_FROM_PATCH(_model_module, patch);
        XOBJECT_SET_PROPERTY_FROM_PATCH(_model_module_version, patch);
        // [...]
    }
```

## Proposed mechanism

The new patch type would comprise

 - a `xeus::xjson` object
 - a list of buffers.

Function `XOBJECT_SET_PATCH_FROM_PROPERTY` would take in a patch **by reference** and append buffers to the current list of buffers. Instead of populating a list of path like in the protocol, the `JSON` object would be populated with the index of the buffer prefixed with `@buffer_ref@`.

Function `XOBJECT_SET_PROPERTY_FROM_PATCH` can compose the property from the `JSON` object and the buffer references.

This new format would be the proposed schema for `ipywidgets 8.0`. In the mean time, we would post-process resulting patches to remove buffer refs and produce a list of paths.

**Comment by maartenbreddels** [comment]
> Function XOBJECT_SET_PATCH_FROM_PROPERTY would take in a patch by reference and append buffers to the list of buffers. Instead of populating a list of paths like in the protocol, the JSON object would be populated with the index of the buffer prefixed with @buffer_ref@.

Is it possible to keep this internal to xeus, meaning we don't change the schema, but it is just a implementation default for xeus?  I don't like so much the idea of magic strings.. but maybe the idea will grow on me.. :)
Are there strong reasons to do this, is maybe the choice for using xjson not a good option? For instance in Python we use a dict, not a json type, the json is just a wire transfer format.

**Comment by SylvainCorlay** [comment]
The issue with the intermediary lists and dicts is that there is really no such option in C++ of arbitrary nested containers that can container *anything*, or when there are, they are are incredibly complex. nlohmann's `json` is already quite flexible and requires a lot of meta-programming and templates.

The key here is to be able to skip the intermediary representation from the object to the message, by incrementally editing the patch message with each property, and inversely to read a property from a message without having to produce this intermediary representation.

For the latter issue, in the current protocol, getting a single property value from a patch containing multiple property changes would require a lookup into the `buffer_paths` to filter for those that correspond to that single property.

**Comment by SylvainCorlay** [comment]
Now, on your question on whether this could be only internal to `xwidgets`, yes, we can shim the current behavior as a post-processing stage, but I think that this proposal is better for the reason detailed above.

Regarding magic strings, we already use them for widget models (`IPY_MODEL_{HASH}`). Now, I realize that we should have probably made that magic string a bit more complex like `@jupyter-widget@{HASH}`, and for the buffer path, have `@buffer-reference@{INDEX}`.

**Comment by maartenbreddels** [comment]
Ok, that is the answer I expected, and a fair point. So the question is basically, do we want C++ 'limitations' to influence the schema. Given that xeus can be the basis for other languages, I think it is fair, and other languages may have a similar limitation.

And I think if we change this, indeed it makes sense to use @jupyter-widget@{hash} indeed.
It has my blessing 👍

**Comment by SylvainCorlay** [comment]
> Ok, that is the answer I expected, and a fair point. So the question is basically, do we want C++ 'limitations' to influence the schema. Given that xeus can be the basis for other languages, I think it is fair, and other languages may have a similar limitation.

(Also, the incremental editing of patches has some efficiency benefits I guess, but I don't think that it is a limiting factor.)

What we intend to do is implement this in xeus, with the shim for the current schema, make a proposal for adopting the new schema in `ipywidgets 8.0`, and remove the shim if it is adopted.

**Comment by maartenbreddels** [comment]
Sound like a good plan, I'm convinced.

**Comment by jasongrout** [comment]
I think this makes a lot of sense, but I would say let's not use them as "magic strings" per se, but instead in the model spec (like https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/schema/jupyterwidgetmodels.v7-1.md), we should explicitly list out where we expect to find binary buffers and encode that in the deserializer. We already basically do this for the IPY_MODEL, but we don't carry it all the way out in js. For example, in https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/schema/jupyterwidgetmodels.v7-1.md#boxmodel-jupyter-widgetscontrols-110-boxview-jupyter-widgetscontrols-110, the `children` attribute should say `array of Widget refs`, and the deserializer should explicitly know that it will find an array of widget refs in that attribute.
