### ISSUE TITLE
Using xwidgets outside of Xeus

### ISSUE THREAD

**Issue by kylekyle** [QuantStack/xwidgets#93]
Chatted with some of you folks at JupyterCon about using xwidgets to add widget support to languages that can make calls to C libraries (using FFI, for example). Everyone seemed to think that would be fairly straightforward. 

I've been playing with idea, but it looks like the widget comms are tied specifically to the xeus kernel in [xtransport.hpp](https://github.com/QuantStack/xwidgets/blob/2872f1620866a209d8466aa3dea189cfca184ec3/include/xwidgets/xtransport.hpp#L64). Is it possible to abstract the comms layer in such a way that any kernel could use a widget by supplying their ZMQ connection information directly?

**Comment by SylvainCorlay** [comment]
Sorry for not responding earlier. You can make another xeus-based kernel (than the C++ kernel) and make use of xwidgets, but I don't think that it is straightforward to make use of them in a non-xeus kernel at the moment.
